{% set name = "jupyterlab_pygments" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pygments-{{ version }}.tar.gz
  sha256: 7405d7fde60819d905a9fa8ce89e4cd830e318cdad22a0030f7a901da705585d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True # [py<37]

requirements:
  host:
    - python
    - pip
    - jupyter-packaging >=0.10,<1
  run:
    - python
    - pygments >=2.4.1,<3
  run_constrained:
    - jupyterlab >=3.1,<4

test:
  imports:
    - jupyterlab_pygments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JupyterLab/jupyterlab_pygments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pygments syntax coloring scheme making use of the JupyterLab CSS variables'
  description: |
      The goal is to enable the use of JupyterLab's themes with pygments-generated HTML.
  dev_url: https://github.com/JupyterLab/jupyterlab_pygments
  doc_url: https://github.com/jupyterlab/jupyterlab_pygments

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
