{% set name = "jupyterlab_pygments" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pygments-{{ version }}.tar.gz
  sha256: 721aca4d9029252b11cfa9d185e5b5af4d54772bb8072f9b7036f4170054d35d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python
    - pygments >=2.4.1,<3
  run_constrained:
    - jupyterlab >=4.0.0,<5.0.0

test:
  imports:
    - jupyterlab_pygments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JupyterLab/jupyterlab_pygments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pygments syntax coloring scheme making use of the JupyterLab CSS variables'
  description: |
      The goal is to enable the use of JupyterLab's themes with pygments-generated HTML.
  dev_url: https://github.com/JupyterLab/jupyterlab_pygments
  doc_url: https://github.com/jupyterlab/jupyterlab_pygments

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
