travis:
  secure:
    BINSTAR_TOKEN: iJUvKsDdLAZ5uxj/hpwKp+TKuHMgCOtRyqbBTS2hRAVatrs17l9/gLOF0HoPVzPtr5cKMAaCPXCOXRL+orfZJcZyxjVsnvEw5l01DbImN38tJFUFUv6vFDRU3hxYvnjlzCRl22yqBIzZZHN3XSg6mI3iAa6OgPmz0COTm9PUYRP2gnTU6bcmUqk5imF0PMgw4oNMWIVrpxPbtsgPokttJNf7MvmTM0QDrunymFBz9IGy4ePWx85iT62yZw507jZGz45psHrzxHwQEMcpH7TwrqALGZo5cZL799Z4ieVzPrPP2i7sLuMjOjQUP5t73npirAT9cXdkQbo31f0Q68XlF+cDO0a7BOcbnYZYvEoR4GJxc4XMdqG0Tm/ik6ZvC7OX1E6gFsp1S5DpFYryOarOn6Qx/rvpxGGb/xjjeGip8fJ6jiCoWcQBPXWY/fGBw2Rh9i8Uoxp4o3vHhiWKOGV5lYgCy8RFuQp4TTPmVlC26m8H0R1UaJQJAEiM3We/RhigGnHmQPY0f7cWtPf6TTZrfn7RGkuJohHoA4jHKTxbpKX6bnX+d4VTtmZeqkbj+oHh4jsnWMveHD6F+QknQIqZcR1E836VJATkwMLqBkWhunB9xmU/tuOuBX7X6lTsggAhwScZr6tJ6d7nOpVOKgT32/axEpBlNLbZV/OlLGaq5CA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
